repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: ^env/
      - id: check-added-large-files
        exclude: ^env/
      - id: trailing-whitespace
        exclude: ^env/
      - id: end-of-file-fixer
        exclude: ^env/
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: ^env/
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        exclude: ^env/
  - repo: https://github.com/pycqa/isort
    rev: "6.0.1"
    hooks:
      - id: isort
        exclude: ^env/|^api/migrations/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        exclude: ^env/
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0 
    hooks:
      - id: markdownlint
        args: [--fix] 
        exclude: ^env/
  - repo: https://github.com/textlint/textlint
    rev: v13.5.1
