version: "3.9"
services:
  database:
    build: ./database
    container_name: sqlite_db
    volumes:
      - sqlite-data:/data
    networks:
      - my-bridge
    restart: always


  app:
    build: ./
    container_name: api
    depends_on:
      - database
    volumes:
      - sqlite-data:/app/database
    networks:
      - my-bridge
    restart: always
    ports:
      - "8000:8000"

volumes:
  sqlite-data:

networks:
  my-bridge:
    driver: bridge