version: "3.9"

services:
  database:
    build: ./database
    container_name: sqlite_db
    volumes:
      - sqlite-data:/data
    networks:
      my-bridge:
        ipv4_address: 172.20.0.2
    restart: always

  app:
    build: ./
    container_name: api
    depends_on:
      - database
    volumes:
      - sqlite-data:/app/database
    networks:
      my-bridge:
        ipv4_address: 172.20.0.3
    restart: always


  load_balancer:
    build: ./load_balancer
    container_name: load_balancer
    restart: always
    depends_on:
      - database
      - app
      - frontend1
      - frontend2
      - frontend3
    networks:
      my-bridge:
        ipv4_address: 172.20.0.4
    ports:
      - "80:80"

  frontend1:
    build: ./frontend
    container_name: frontend1
    restart: always
    depends_on:
      - database
      - app
    networks:
      my-bridge:
        ipv4_address: 172.20.0.11

  frontend2:
    build: ./frontend
    container_name: frontend2
    restart: always
    depends_on:
      - database
      - app
    networks:
      my-bridge:
        ipv4_address: 172.20.0.12

  frontend3:
    build: ./frontend
    container_name: frontend3
    restart: always
    depends_on:
      - database
      - app
    networks:
      my-bridge:
        ipv4_address: 172.20.0.13

volumes:
  sqlite-data:

networks:
  my-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
