name: Deploy-to-EC2 instance

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # set env
            echo "${{ secrets.ENV }}" > /home/ubuntu/app/.env
            sudo apt update
            sudo chmod +x /home/ubuntu/ubuntu
            sudo chmod +x /home/ubuntu/app
            # set env for health check
            echo 'SERVER_HEALTH_LOG="${{ secrets.SERVER_HEALTH_LOG }}"' >> ~/.env
            chmod +x /home/ubuntu/app/backup_scripts/health_check.sh
            chmod +x /home/ubuntu/app/backup_scripts/update.sh
            chmod +x /home/ubuntu/app/backup_scripts/backup_api.sh

            sudo docker-compose down
            sudo docker container prune -f
            sudo docker-compose -f /home/ubuntu/app/docker-compose.yml up --build -d