name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  DEBUG: 'true'
  SECRET_KEY: 'django-insecure-=x9l_0fdkt-1se8lyt3qr-wq2fmatlj_v^tm8o3^viq!*5tq@6'

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: production

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.8, 3.11.9, 3.12.8]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
